steps:

- id: 'bump tag'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'wget -O - https://raw.githubusercontent.com/treeder/bump/master/gitbump.sh | bash']

- id: 'docker build backend'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-west1-docker.pkg.dev/gitlab-fiddle/docker/backend:$TAG_NAME', 'backend']
  
- id: 'docker push backend'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-west1-docker.pkg.dev/gitlab-fiddle/docker/backend:$TAG_NAME']