steps:
- id: 'set up github ssh'
  name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp cloudbuild/known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- id: 'define next tag'
  name: 'gcr.io/cloud-builders/nodejs/yarn'
  entrypoint: 'bash'
  args: ['-c', './scripts/get-bumped-git-tag.sh > /workspace/next-tag.txt']

- id: 'docker build backend'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build -t us-west1-docker.pkg.dev/gitlab-fiddle/docker/backend:$(cat /workspace/next-tag.txt) backend']
  
- id: 'docker push backend'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker push us-west1-docker.pkg.dev/gitlab-fiddle/docker/backend:$(cat /workspace/next-tag.txt)']

- id: 'apply next tag'
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - -c
  - |
    git clone git@github.com:sfishel18/gitlab-fiddle.git
    cd gitlab-fiddle
    git tag -a "$(cat /workspace/next-tag.txt)" -m "$(cat /workspace/next-tag.txt)"
    git push --tags
  volumes:
  - name: 'ssh'
    path: /root/.ssh

availableSecrets:
  secretManager:
  - versionName: projects/1023756473676/secrets/SSH_KEY/versions/latest
    env: 'SSH_KEY'