steps:
- id: 'define next tag'
  name: 'gcr.io/cloud-builders/nodejs/yarn'
  entrypoint: 'bash'
  args: ['-c', './scripts/get-bumped-git-tag.sh > /workspace/next-tag.txt']

- id: 'docker build backend'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build -t us-west1-docker.pkg.dev/gitlab-fiddle/docker/backend:$(cat /workspace/next-tag.txt) backend']
  
- id: 'docker push backend'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker push us-west1-docker.pkg.dev/gitlab-fiddle/docker/backend:$(cat /workspace/next-tag.txt)']

- id: 'apply next tag'
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args: ['-c', 'git tag -a $(cat /workspace/next-tag.txt) && git push --tags']
  env: ['EMAIL=cloud-build@gitlab-fiddle.com']