apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: backend
  namespace: gitlab-fiddle
spec:
  image: us-west1-docker.pkg.dev/gitlab-fiddle/docker/backend
  interval: 10m0s
  secretRef:
    name: gcloud-artifact-registry
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: backend
  namespace: gitlab-fiddle
spec:
  imageRepositoryRef:
    name: backend
  policy:
    semver:
      range: 0.x