apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-deployment-secrets
  namespace: gitlab-fiddle
spec:
  encryptedData:
    GITLAB_API_TOKEN: AgB0/3tRNwphVV7cTkXrkYQPruWpTG9KBo+RNBFWc9PSiF1e3PagLKXsBRTsk5J9nrgd+5LVz+2WrGpYaZS6UimUK8HkU91cdaCEgxXC46FAHmnIpMcFLMUdMVA9PjNgPbALzFqUx8SDTXXbxjYXRhvqKV4lvF1nUimNOXTKLkEujP+4YFNFptV31anqXiqJJaciMI40itijVVv0yHCoTYEH/MYsTuq51EYECvo1f2W+6AvNout2D+fwx7RWOq5a7QGp0KtioJRuOYmThuPj8aKwKI0aiSHlt6t6hegwQsEEaVkxZQVWQxMqVFvmkyEF1gZ0lqG8mu9zlKODZ/ZP8aaQM8thzedq4/zmTwZRZJusHlk7FWHg4rJDNuH0YOqeTFFALebKlSaHOXBDLTMJO4Zc2iJkp4ypTr3RHQregQzjQ8jL6bH9qfYlid5cRrs/12cZEHuldsx6jnI6DZGKjlAkRE/+HIehTOJcQsoD6VINcZibpj7RlsUwHMi+b81j15Wq+XrNGCm826gL/KfbRlKbQs/EZi/z5FvuVVK+WyljYJ7KRD1M3BcPfaqM3WloCRgSnU1lnEYmvS8BXkIQXXxdTUfsLzwMvn9d+BIZAZe/h8Kv/d+U4NDe78TXp+U2PY1btnuuI1WN/by3SyWnNGXHjeMdG+8Mh/CcC39HtqJ+98fhq8PumCMa13fW27u1I0Zv7ggRsiiuNgkgKqZb+xOisv/oVQ==
    GITLAB_TRIGGER_TOKEN: AgBut8c/a+ceRTAa4el/pRNI2GF+mUCVdK86NKHPyD5N0cRXqEIUCwdkRNJu9VwBllxUwwivnMnp7PWAyOcXEgq/SY0UT20ioKUdwdaI750Yg7uuBOy2ZWqlzZgZMQh0vYDf8Tq7eKRG0Oxd7J5rKQJOF0288+Mc0K6zdNQrIzuc4JjwIMNqsAfbu1tI5qDsl1ZAGSp66JPYkkUaY02Wm+jTCshdjRQs3kcnHX2oK8Bv9zATitUrxQjOLaO9D+GWyR+0+xzAgr+qSgTfk7ZLrVSykmDY0FuMgU3enaohCxKiwzxj6jC0PoEYldr/KBp21KW1e1DPwoZ+xaB/skTxqrAqgsxfxadVxIwPrTciNQZw43J+4YoH4YGHhz0B/+sQ4nr+8sSuDfc0WQYMyZDwF8LTKTSLki8RhBYWVacjwRXGWkaE9kDFo/qE+a/gYxj4Yh9VPbOn+7db+L/rGNGHuEnPt1/V8CLGSiJkD6diaUrCzSI2Tma9TSbSAg4sSyzFYPikaVFHBdvXIBu0Wofkl/adfpHkWt1Mkz+c+1OiBSWnL0Ch7+Kyc6kDLQsL5HdDHTfNHkjOgfH2hYAWcqrG4ABviCpFKndUooSQz4jzcNb4HC6UJPGN/xww6nG0XWn1dHIqAqUnsiKgv1gRToGvB4TGbmxx16oGtDBfEvbfWmpoDRJ5sMPUhQg/D1/Cg+s4ARFJnKm9/WwL9A1YYRcPu2W8K759kdMcGFYf9e0zEJU=
  template:
    metadata:
      name: backend-deployment-secrets
      namespace: gitlab-fiddle
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-fiddle-backend-deployment
  labels:
    app: gitlab-fiddle-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-fiddle-backend
  template:
    metadata:
      labels:
        app: gitlab-fiddle-backend
    spec:
      containers:
        - name: gitlab-fiddle-backend
          image: us-west1-docker.pkg.dev/gitlab-fiddle/docker/backend:v0.0.17 # {"$imagepolicy": "gitlab-fiddle:backend"}
          ports:
            - containerPort: 3000
          env:
            - name: GITLAB_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backend-deployment-secrets
                  key: GITLAB_API_TOKEN
            - name: GITLAB_TRIGGER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backend-deployment-secrets
                  key: GITLAB_TRIGGER_TOKEN
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
      imagePullSecrets:
        - name: gcloud-artifact-registry
