apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-fiddle-frontend-deployment
  labels:
    app: gitlab-fiddle-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-fiddle-frontend
  template:
    metadata:
      labels:
        app: gitlab-fiddle-frontend
    spec:
      containers:
        - name: gitlab-fiddle-frontend
          image: us-west1-docker.pkg.dev/gitlab-fiddle/docker/frontend:v0.0.18 # {"$imagepolicy": "gitlab-fiddle:frontend"}
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: gcloud-artifact-registry
