apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab-fiddle
images:
  - name: us-west1-docker.pkg.dev/gitlab-fiddle/docker/backend
    newName: us-west1-docker.pkg.dev/gitlab-fiddle/docker/backend
    newTag: 0.0.4 # {"$imagepolicy": "gitlab-fiddle:backend:tag"}
resources:
  - namespace.yaml
  - image-pull-secret.yaml
  - backend-image-sync.yaml
  - backend-deployment.yaml
  - backend-service.yaml