apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab-fiddle
resources:
  - namespace.yaml
  - image-pull-secret.yaml
  - backend-image-sync.yaml
  - image-update-automation.yaml
  - backend-deployment.yaml
  - backend-service.yaml