apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: pipeline-simulator
spec:
  selector:
    app: gitlab-fiddle-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000